### ISSUE TITLE
fred fails to install when bcmath not available

### ISSUE THREAD

**Issue by roland2025** [modxcms/fred#201]
fred installer should check if bcadd etc functions are available, otherwise fails to install and when installing again (after installing php-bcmath) multiple policies are added, end result is fred doesn't work.

` [php7:error] [pid 10687] [client ::1:34116] PHP Fatal error:  Uncaught Error: Call to undefined function Moontoast\\Math\\bcadd() in /var/www/html/modx/core/components/fred/model/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php:506\nStack trace:\n#0 /var/www/html/modx/core/components/fred/model/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php(62): Moontoast\\Math\\BigNumber->setValue('155553821766506')\n#1 /var/www/html/modx/core/components/fred/model/vendor/ramsey/uuid/src/Converter/Number/BigNumberConverter.php(49): Moontoast\\Math\\BigNumber->__construct('155553821766506')\n#2 /var/www/html/modx/core/components/fred/model/vendor/ramsey/uuid/src/Generator/CombGenerator.php(69): Ramsey\\Uuid\\Converter\\Number\\BigNumberConverter->toHex('155553821766506')\n#3 /var/www/html/modx/core/components/fred/model/vendor/ramsey/uuid/src/UuidFactory.php(217): Ramsey\\Uuid\\Generator\\CombGenerator->generate(16)\n#4 /var/www/html/modx/core/components/fred/model/fred/src/Utils.php(113): Ramsey\\Uuid\\UuidFactory->uuid4()\n#5 /var/www/html/modx/core/components/fred/model/fred/fredtheme.class. in /var/www/html/modx/core/components/fred/model/vendor/moontoast/math/src/Moontoast/Math/BigNumber.php on line 506, referer: http://localhost/modx/manager/?a=workspaces`

**Comment by roland2025** [comment]
Might also be related to bug #65 and #69
